### ISSUE TITLE
Moving from odin-color to odin-terminal

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/odin-color#12]
Moving away from being a package just for ANSI colours and adding support for text styling, cursor movements, better colours, and improved cross-platform support.

The aim of the package (called `odin-terminal` going forward) will be an high-level API to interact with the terminal.

I will split the package up into sub-packages:
- **graphics**: colors (8-bit, RGB, etc) and effects (blink, underline, etc)
- **cursor**: moving the cursor around, 
- **screen**: changing screen width, colour mode, etc
- **keyboard**: detecting key presses in the terminal
- **mouse**: mouse position, clicking, scrolling, etc
- **termios**: C foreign bindings for termios.h
- **clipboard**: access to copy/paste
- **sound**: making beeps and boops

Related issues:
- #6 
- #7 
- #8 
- #9 
- #10 

### Roadmap
- [ ] Graphics package:
  - [ ] Move colour api to graphics package
  - [ ] Add rgb and on_rgb
  - [ ] Add text styles
  - [ ] Examples for the graphics package
- [ ] Set up GitHub Actions to test all examples
- [ ] Cursor package:
  - [ ] Cursor controls api
  - [ ] Cursor erasing methods
  - [ ] Cursor visibility
  - [ ] Examples for cursor package
